/*
 * This Groovy source file was generated by the Gradle 'init' task.
 * 
 * 
 * https://medium.com/@chinthakadinadasa/develop-a-cli-tool-using-groovy-scripts-a7d545eecddd
 */
package org.quipa.dialogo

class App {

    static void main(String[] args) {
        println "Bem-vindo ao 'Dialogo'!"
        // println "SPAM"
        def interpretador = new Interpretador()
        def console = System.console()
        String frase = ""
        while (frase != "sair") {
            // this doesn't work when running through gradle run
            // use gradle installDist and ./app/build/install/app/bin/app
            frase = console.readLine(' - ')
            
            switch (frase) {
                case "história":
                    println(interpretador.história)
                    break
                default:
                    println("   " + frase)
                    interpretador.história += "${frase}\n"
            }
            
        }
    }
}

class Interpretador {
    String história = ""
    
    List<String> ler(String texto) {
        return texto.tokenize()
    }
    
    List<String> avaliar(List<String> items) {
        return items
    }
    
    String imprimir(List<String> items) {
        return items.join()
    }
}
